spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${oauth2.google.client-id}
            client-secret: ${oauth2.google.client-secret}
            redirect-uri: ${oauth2.google.redirect-uri}

          naver:
            client-id: ${oauth2.naver.client-id}
            client-secret: ${oauth2.naver.client-secret}
            redirect-uri: ${oauth2.naver.redirect-uri}

          kakao:
            client-id: ${oauth2.kakao.client-id}
            client-secret: ${oauth2.kakao.client-secret}
            redirect-uri: ${oauth2.kakao.redirect-uri}

        provider:
          naver:
            authorization_uri: ${oauth2.provider.naver.authorization_uri}
            token_uri: ${oauth2.provider.naver.token_uri}
            user-info-uri: ${oauth2.provider.naver.user-info-uri}

          kakao:
            authorization-uri: ${oauth2.provider.kakao.authorization_uri}
            token-uri: ${oauth2.provider.kakao.token_uri}
            user-info-uri: ${oauth2.provider.kakao.user-info-uri}

          google:
            user-info-uri: ${oauth2.provider.google.user-info.uri}
