oauth2:
  google:
    user-info-uri: https://www.googleapis.com/userinfo/v2/me
  kakao:
    user-info-uri: https://kapi.kakao.com/v2/user/me
  naver:
    user-info-uri: https://openapi.naver.com/v1/nid/me

spring:
  h2:
    console:
      enabled: true

jwt:
  secret-key: secret-key
  access:
    expiration: 100000000
  refresh:
    expiration: 10000000000
