oauth2:
  google:
    user-info-uri: https://www.googleapis.com/userinfo/v2/me
  kakao:
    user-info-uri: https://kapi.kakao.com/v2/user/me
  naver:
    user-info-uri: https://openapi.naver.com/v1/nid/me

spring:
  datasource:
    url: jdbc:h2:~/haru-dongseon;MODE=MySQL
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

jwt:
  secret-key: secret-key
  access:
    expiration: 100000000
  refresh:
    expiration: 10000000000
